### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRApp

### ISSUE THREAD

**Issue by otaviolbarbosa** [Autofleet/locomotion#827]
Hi,

I'm trying to run locomotion on iOS, but I got the following error message.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
       in AppDelegate.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
       in AppDelegate.o
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
       in AppDelegate.o
  "_RCTAppSetupDefaultRootView", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTAppSetupPrepareApp", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

On Android, I was bale to run it without problems, but still struggling with iOS version. Any ideas on how to fix it?

### Steps to reproduce:
```
Macbook Air M2, 2022
React Native version : 0.68.5
Node version : v14.21.3
Xcode version : 15.4 (15F31d)
Destination: iPhone 15
SDK Simulator: iOS 17.5
```

**Comment by sephina** [comment]
Hi @otaviolbarbosa 

Is your destination a real device or simulator? from Xcode or command line?
Also I just want to validate that pod install ran successfully.

**Comment by otaviolbarbosa** [comment]
Hi @sephina, thanks for your reply.

I'm trying to run it on simulator. I did try both Xcode and command line. Above error message is from command line, But I get similar error on Xcode, see next image.

<img width="1470" alt="image" src="https://github.com/Autofleet/locomotion/assets/4713316/aef8ba8a-1b71-4e05-b603-475446a814ca">

**Comment by sephina** [comment]
@otaviolbarbosa Can you try using a Rosetta simulator instead of the one you're using?
If you don't see any try `Product -> Destination -> Show all run destinations` and then choose any device tagged with Rosetta.

**Comment by otaviolbarbosa** [comment]
> @otaviolbarbosa Can you try using a Rosetta simulator instead of the one you're using? If you don't see any try `Product -> Destination -> Show all run destinations` and then choose any device tagged with Rosetta.

Ok, I miss that! Thanks for your help, @sephina.
