### ISSUE TITLE
Unable to generate Price and ETAs

### ISSUE THREAD

**Issue by nusjose** [Autofleet/locomotion#830]
I get an error with status code 500 when fetching the /estimations API

![Screenshot 2024-07-10 at 09 24 33](https://github.com/Autofleet/locomotion/assets/85001828/6e90a753-2c51-4046-b0b8-285cef867066)

My cURL
```
curl --location 'https://api.autofleet.io/api/v1/estimations' \
--header 'accept: application/json' \
--header 'authorization: Bearer {{authToken}}' \
--header 'content-type: application/json' \
--data '
{
  "queries": [
    {
      "rideType": "passenger"
    }
  ],
  "includePrice": true,
  "includeETA": true,
   "stopPoints": [
    {
      "type": "pickup",
      "lat": 43.642566,
      "lng": -79.387057
    },
    {
      "type": "dropoff",
      "lat": 45.507452,
      "lng": -73.587749
    }
  ],
  "demandSourceId": "{{demandSourceId}}",
  "businessModelId": "{{businessModelId}}"
}
``` 
Any ideas on how to fix it?

**Comment by OmerGery** [comment]
Hey again @nusjose 
1. try to follow the same format of request that the locomotion app makes 
2. change base url to client.autofleet.io 
3. please provide with the x-trace-id from the response headers

**Comment by otaviolbarbosa** [comment]
@OmerGery We got the data after changes, thanks!

**Comment by OmerGery** [comment]
glad to help @otaviolbarbosa
