### ISSUE TITLE
 Make a ride request for testing

### ISSUE THREAD

**Issue by uri-jeff** [Autofleet/locomotion#832]
Hi Team, 
I am testing the creation of a ride request, but the application requires real VISA card information. How can I configure a test card for this purpose? I tried adding the test publishable key, but I received an error message.
Thank you,

![Screenshot 2024-07-16 at 11 35 26](https://github.com/user-attachments/assets/d2b6f4ab-f678-4e55-a272-b2967d8f2655)

**Comment by OmerGery** [comment]
Hey @uri-jeff,
In our production enviroment (client.autofleet.io server), test cards are not supported, thats why the stripe test key won't work.
2 options to work around it: 
1. allow cash or offline payment in your autofleet enviroment, then you can create a ride without a card.
2. debug the locomotion app connected to our staging enviroment (https://client.staging.eu.autofleet.io/ server) , perquisite is to have an autofleet staging enviroment.

**Comment by uri-jeff** [comment]
Hi @OmerGery, 
we have finished setting up the staging environment but still get error 500 when logging in. We tried with both endpoints: https://client.staging.eu.autofleet.io, https://client.autofleet.io got the same error message


https://client.staging.eu.autofleet.io: 
`
curl --location 'https://client.staging.eu.autofleet.io/api/v1/login/vert' \
--header 'Content-Type: application/json' \
--header 'x-loco-ds-id: xxx' \
--header 'x-loco-op-id: xxx' \
--data '{"code":"xxx","demandSourceId":"xxx","phoneNumber":"181063714xx"}'

{"status":"ERROR","traceId":"BiHEcFQca"}`

{"status":"ERROR","traceId":"VjPMi5u6q"}`

https://client.autofleet.io:
`curl --location 'https://client.autofleet.io/api/v1/login/vert' \
--header 'Content-Type: application/json' \
--header 'x-loco-ds-id: xxx' \
--header 'x-loco-op-id: xxx' \
--data '{"code":"2869","demandSourceId":"xxx","phoneNumber":"131728496xx"}'

{
    "status": "ERROR",
    "traceId": "iz53S1MZPQ"
}`

not sure what we missed? can you please take a look, thanks
