### ISSUE TITLE
Staging env Login Issue

### ISSUE THREAD

**Issue by uri-jeff** [Autofleet/locomotion#834]
Hi Team,
we have finished setting up the staging environment but still get error 500 when logging in. We tried with both endpoints: https://client.staging.eu.autofleet.io/, https://client.autofleet.io/ got the same error message

https://client.staging.eu.autofleet.io/:
`
curl --location 'https://client.staging.eu.autofleet.io/api/v1/login/vert'
--header 'Content-Type: application/json'
--header 'x-loco-ds-id: xxx'
--header 'x-loco-op-id: xxx'
--data '{"code":"xxx","demandSourceId":"xxx","phoneNumber":"181063714xx"}'

{"status":"ERROR","traceId":"BiHEcFQca"}`

{"status":"ERROR","traceId":"VjPMi5u6q"}`

https://client.autofleet.io/:
`curl --location 'https://client.autofleet.io/api/v1/login/vert'
--header 'Content-Type: application/json'
--header 'x-loco-ds-id: xxx'
--header 'x-loco-op-id: xxx'
--data '{"code":"2869","demandSourceId":"xxx","phoneNumber":"131728496xx"}'

{
"status": "ERROR",
"traceId": "iz53S1MZPQ"
}`

not sure what we missed? can you please take a look, thanks

**Comment by OmerGery** [comment]
looking into it

**Comment by OmerGery** [comment]
For visibility: we connected our payment service to your demand source id in our staging env.
