### ISSUE TITLE
"Captcha failed" error with login API

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#835]
I always get a "captcha failed" error when I fetch API /login. Here is my cURL

```
curl --location 'https://client.staging.eu.autofleet.io/api/v1/login' \
--header 'Content-Type: application/json' \
--data '{
"allowedDemandSourceIds":[],
"channel":"sms",
"demandSourceId":"{{demandSourceId}}",
"phoneNumber":"12512790623"
}'
``` 
![Screenshot 2024-07-29 at 14 17 37](https://github.com/user-attachments/assets/6f0ac4be-ba95-4fb2-a2bd-9b255972ac8f)

Can you please take a look, thanks

**Comment by OmerGery** [comment]
Hey we will follow up over email

**Comment by OmerGery** [comment]
handled via mail
