### ISSUE TITLE
Unable to verify user email.

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#836]
I registered with my email address "jose@uridetech.com" but I haven't received any verification email yet. I've also checked my spam folder, but I still haven't received anything.

Based on the Locomotion app, the setup intent from Stripe added customer email, which is fetched from `/api/v1/me/customers`. However, the API response doesn’t include the email field. After I checked the response from `api/v1/me`, the isEmailVerified field was returned as false.

Could you please provide instructions on how to verify my email?

**Comment by OmerGery** [comment]
Hey,
Make sure you make the same api requests as the app makes in the onboarding process (from the ui)
