### ISSUE TITLE
How to update Driver status?

### ISSUE THREAD

**Issue by uri-jeff** [Autofleet/locomotion#837]
Hi Team,

After I create a Ride from Passenger, how can I update the status from Driver: accepted/rejected/ completed a ride? I checked the Driver related settings on the control panel but didn’t see it, Can we update this through API? any details regarding this?

Thanks Team,

**Comment by OmerGery** [comment]
Hey, 
1. Updating driver/ride states is through the fleet manager api ( https://api.autofleet.io/ ) and not ( https://client.staging.eu.autofleet.io/ ). it's out of scope for clients / locomotion  to change that
2. Changing a ride to completed is through arriving/completing stop points , not directly changing the ride state.

**Comment by 6ewis** [comment]
About your point #2, Can you clarify how would you do that? What endpoint would you use to generate fake rides, and drivers status to test ? @OmerGery

**Comment by michalbanin** [comment]
@6ewis you have a few options here:
1. You can activate a few drivers that will accept rides in the staging env, and complete rides through the env: 
- create fake drivers through the fleet section > drivers tab
- set them with the "Uride vendor" (which is an auto accept vendor)
- create a few fake vehicles through the fleet section > vehicles tab
- in the main dashboard, switch to the vehicles tab > click on a vehicle > switch to the "driver" tab > click on "assign driver" and select one of the drivers
- after you create a ride, it should go to one of the drivers automatically. if it doesn't (drivers are located to far for example) you can force the ride to one of the drivers. 
- after a ride is assigned to a driver you can manually complete or cancel the ride through the dashboard. 

2. Through API
- create rides through the clients API so it will mimic locomotion/ through locomotion
- ride and driver states will be handled through the [Autofleet APIs](https://api.autofleet.io/)  - instructions are detailed in the docs

**Comment by uri-jeff** [comment]
I was able to update the status of the driver through updating Stop points, thanks for clarifying

One more question regarding ride tracking: Is there a way to simulate the driver's location so I can see the driver moving to the pickup and drop-off points? and through which API can I get the driver's location - in real time?

Thanks @michalbanin

**Comment by uri-jeff** [comment]
@michalbanin @OmerGery  Can you please take a look? Also, can I update the status of stop points to "arrived"? Currently I can only update -> "completed" through admin panel

**Comment by michalbanin** [comment]
Unfortunately there is no way to simulate a driver's real time location in the staging env. In your testing env (production) we can activate fake drivers that will move around and simulate drivers completing rides. 
When completing rides through the Control Center, you can only complete and not mark arrived.

**Comment by 6ewis** [comment]
@michalbanin basically we have to go back to use the production environment to test

**Comment by michalbanin** [comment]
Only if you want to simulate real time location
Another option is to connect as drivers to the staging env and complete trips through the driver app (and move around with the app).
How to do this:
1. Register yourself as a driver in the staging env (fleet section > drivers tab)
2. Download the uride driver app
3. Access [this](https://europe-west1-autofleetprod.cloudfunctions.net/deeplink-redirect/set-hosts?vldmsUrl=ws://35.241.45.160&driverUrl=http://35.241.45.160/) link, it will open the driver app
4. Log in using the phone number you registered 
5. Create trips and complete them through the driver app

**Comment by michalbanin** [comment]
@uri-jeff just wanted to update- you can update a stop point to "arrived" via API - post:
https://control.autofleet.io/api/v1/vehicles/xxxxxx/stop-points/yyyyyy/arrived
xxxxxx= vehicleId
yyyyyy= stopPointId

**Comment by uri-jeff** [comment]
@michalbanin Can I test on staging environment? I get a 404 error when trying with your suggestion above

curl --location 'https://client.staging.eu.autofleet.io/api/v1/vehicles/13390072-4dc3-45d0-8868-17f23bc73a50/stop-points/59ab4248-7bef-481f-a061-5d552620daf2/arrived' \
--header 'x-loco-ds-id: xxx' \
--header 'x-loco-op-id: xxx' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNGNjMjdjZTEtZmY1Ny00ODIzLThkMmUtMmE2OTNkZDQ5OTdmIiwiYWNjb3VudFR5cGUiOiJjbGllbnQifSwiZGVtYW5kU291cmNlSWQiOiJkMzMzZjMxZC1iZDU1LTRjOGItODdiMC1iNmQxNWM1MmVlY2YiLCJpYXQiOjE3MjQ3NDMzNDAsImV4cCI6MTcyNDgyOTc0MCwianRpIjoielBpUUVpODdSIn0.cp2ryQPo8P72Fy-bqzSocXLJTHDI9Gk4UkCoXIVc2w8'

<img width="973" alt="Screenshot 2024-08-28 at 14 28 50" src="https://github.com/user-attachments/assets/50b41e57-db7e-4323-ab3e-1c950f2a47e0">
