### ISSUE TITLE
Can't get user coupon

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#838]
Hi Team,

I am working on the coupon feature for a ride. However, I encountered this error when fetching the '/me/customers/coupon' API: 'NO_COUPON_ASSIGNED_TO_CUSTOMER'. How can I assign a coupon to a customer? I have tried looking on the Control Panel Admin page, but I couldn't find where to manage these coupons.

![Screenshot 2024-08-05 at 17 02 10](https://github.com/user-attachments/assets/4b9cfab2-5b2d-4a6c-a988-a7e97b799dc1)

**Comment by michalbanin** [comment]
Promo codes are created through stripe, and can be assigned through stripe to specific clients or used by all.
Attaching deck explaining how to create these, you need to create it in your Stripe Staging env, to which our staging env is currently connected. 
[Creating promo codes on Stripe (2).pdf](https://github.com/user-attachments/files/16508647/Creating.promo.codes.on.Stripe.2.pdf)
