### ISSUE TITLE
Payment intent issue - can’t create a Ride and add a payment method

### ISSUE THREAD

**Issue by uri-jeff** [Autofleet/locomotion#839]
Hi Team, 
I got an error about payment -> can’t create a Ride and add a payment method , before that I was able to create it just fine, can you please take a look.
<img width="534" alt="Screenshot 2024-08-06 at 15 02 53" src="https://github.com/user-attachments/assets/435653c2-55fe-4554-bdc3-9315673ac841">
![Screenshot 2024-08-06 at 15 15 48](https://github.com/user-attachments/assets/21843fe0-2e71-4ca2-a8e5-31cc67def68f)
<img width="921" alt="Screenshot 2024-08-06 at 15 16 52" src="https://github.com/user-attachments/assets/c8a0fbbb-81f2-40fa-92e0-6f0faecfcc40">
<img width="1054" alt="Screenshot 2024-08-06 at 15 30 55" src="https://github.com/user-attachments/assets/768f1119-e5b4-4cf2-bc5f-f3bfb339865f">
![Screenshot 2024-08-06 at 15 40 13](https://github.com/user-attachments/assets/528593fa-93f3-496f-8b4b-c896a389480e)

Thanks,

**Comment by michalbanin** [comment]
Hi Jeff,

This is happening because we replaced the Stripe key with yours (it was set up with ours before).
Please try creating a new client.

**Comment by 6ewis** [comment]
@michalbanin we haven't changed the stripe key though? we are using the same key that was originally there - the one you sent with the environment variable cc @OmerGery
