### ISSUE TITLE
Enable cash and offline payment methods

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#841]
Hi team,

I'm working on Cash and Offline payment methods. But I can't enable these options on Control Panel. Can you share with me how to enable them for AF Service?

![Screenshot 2024-08-13 at 13 38 07](https://github.com/user-attachments/assets/a3a7dbfb-400a-4fb0-bd8a-c6d124856e5d)

**Comment by michalbanin** [comment]
We will add this for you and let you know once we're done

**Comment by michalbanin** [comment]
Hi @joseuride , we've added the cash and offline options to the service in the staging env.

**Comment by joseuride** [comment]
Thanks @michalbanin. I will check it

**Comment by tonyuride** [comment]
Hi @michalbanin , I checked the payment cash and offline mode but it's still disabled in control panel.


![Screenshot 2024-08-16 at 15 44 46](https://github.com/user-attachments/assets/fba1f910-b1b0-4bae-b816-361ef15bd40e)

**Comment by michalbanin** [comment]
Hi @tonyuride I'm able to see all options, which client are you selecting?
<img width="666" alt="image" src="https://github.com/user-attachments/assets/7335a45e-8c40-4ddb-bca9-86d3c4b03888">

**Comment by tonyuride** [comment]
@michalbanin Can you set up a ride completely (choose the address to pick up and drop off)?  Then select the payment method and you will see it's disabled.

**Comment by michalbanin** [comment]
Hi @tonyuride, the reason it wasn't working is because the pricing policy you created was set to the "Uride Thunderbay" demand source, and not "Uride Rider", which is the app demand source which the service is connected to. 
It should be working now
![image](https://github.com/user-attachments/assets/9a5d77c9-3549-46e6-afb3-ac44c123da1e)

**Comment by 6ewis** [comment]
@michalbanin you created the pricing policy as per "We set one service, "Thunder Bay car," and one pricing policy for your testing. Thunder Bay's territory is defined, but you can easily edit it in the "Admin" section, "Settings" tab. "

**Comment by 6ewis** [comment]
@michalbanin you set Uride thunder bay "We set one service, "Thunder Bay car," and one pricing policy for your testing. Thunder Bay's territory is defined"

Can you please send invite for "Uride rider" too ?

**Comment by michalbanin** [comment]
@6ewis
 I think there is a confusion here, let me clarify:
There are 2 demand sources in your env:

1. Uride rider (ID c625ee1e-4a13-49ac-b5a8-8d121965c294)- which is the demand source we created for you when we granted you access in July 2024 specifically for the forking process. Services are connected to this demand source, and the pricing policy we created was connected to it as well. 
2. Uride Thunderbay (ID d333f31d-bd55-4c8b-87b0-b6d15c52eecf) - was set up when the env was created during the Uride implementation process, 2 years ago.

It seems that the app you're building is based on the Uride Thunderbay demand source. We have two options:
- We will connect the services and pricing to the Uride Thunderbay demand source
- You can change the app demand source to Uride rider

Let me know which you prefer

**Comment by michalbanin** [comment]
@6ewis Updating that we've connected the services to "Uride Thunderbay" demand source.
The demand source is connected to your stripe account.
