### ISSUE TITLE
Cancellation Reason always empty

### ISSUE THREAD

**Issue by tonyuride** [Autofleet/locomotion#842]
API: /api/v1/rides/${rideId}/cancellation-reasons

Hi team, I'm working on getting the API cancellation reason with 'rideId' (API above) but it always returns empty. I have found a way to add these reasons on the control panel but I don't see it. Can you have a look at this and assist me in adding it?

This is a cURL : 
`curl --location 'https://client.staging.eu.autofleet.io/api/v1/rides/431bbbdc-a2c2-4ca2-80e4-e39e367be778/cancellation-reasons' \
--header 'x-loco-ds-id: {demandSourceId}' \
--header 'x-loco-op-id: {demandSourceId}' \
--header 'Authorization: Bearer token'`

![Screenshot 2024-08-15 at 16 52 17](https://github.com/user-attachments/assets/20be5c33-611b-4536-91fa-d184b398c38e)

**Comment by michalbanin** [comment]
Hi @tonyuride, there were no cancelation reasons set up in the staging env, we added a few now. Can you please check again?
