### ISSUE TITLE
502 (Bad Gateway)

### ISSUE THREAD

**Issue by tonyuride** [Autofleet/locomotion#843]
There seems to be an issue with control.staging.eu.autofleet.io. I believe the server is down.

![image](https://github.com/user-attachments/assets/e95041da-e96c-4eec-b9e5-467b5ca9d02b)
![image](https://github.com/user-attachments/assets/521ee1c6-3232-4fc2-97ed-3d7953581ab0)

**Comment by michalbanin** [comment]
Hi @tonyuride,

Thanks for letting me know, should be resolved now. Can you please check and confirm?

**Comment by tonyuride** [comment]
Hi Michal,

Thank you for your reply! It's working now

Best regards,

Tony
