### ISSUE TITLE
Sign in by email

### ISSUE THREAD

**Issue by otaviolbarbosa** [Autofleet/locomotion#845]
Hello,

@michalbanin is there an endpoint to authenticate users by email? I didn't find it looking in the source code, I was wondering if you have it but it wasn't included in this project.

**Comment by 6ewis** [comment]
by email or SSO

**Comment by michalbanin** [comment]
@otaviolbarbosa email verification is needed for sending invoices and receipts. Therefore, it is done by Stripe, and not directly by Autofleet.

**Comment by otaviolbarbosa** [comment]
@michalbanin What I mean is a way to authenticate users by email or SSO. Currently, this flow is made by using phone number, right?

**Comment by michalbanin** [comment]
@otaviolbarbosa Correct, only by phone number
