### ISSUE TITLE
Unable to create a Ride with Credit Card

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#846]
Hi team, I can't create a Ride with a Credit Card on the Admin page now. It says the service is unavailable, please look into this.

![ride2](https://github.com/user-attachments/assets/37f665c5-1d06-432b-b988-3a9537b35db0)

![ride1](https://github.com/user-attachments/assets/3035db81-c0da-4435-a870-6d8f90558b79)

**Comment by tonyuride** [comment]
Sometimes, I encountered an error which prevented me from booking a new ride (even after accessing the admin panel).

![image](https://github.com/user-attachments/assets/b013e7f7-469e-4a65-8052-172a935b2625)

**Comment by michalbanin** [comment]
Hi @joseuride, should be resolved, can you please check?

**Comment by tonyuride** [comment]
Hi @michalbanin , It is working now.
Thank you!
