### ISSUE TITLE
Unable to create the Ride.

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#850]
Hi team, I can't create a ride on the Admin Page now

https://github.com/user-attachments/assets/bc30be88-15d8-43f0-ab51-361655561707

**Comment by michalbanin** [comment]
Hi @joseuride, I understand from our support team that the issue was resolved.

**Comment by tonyuride** [comment]
Hi @michalbanin , Appreciate that! Thank you for supporting our team.
I just want to let you know this issue appears frequently, it's kind of affected our progress for now. We rely on this control panel to handle the booking process. Please let us know if we have done anything wrong or messed up the admin panel to cause this issue.

**Comment by michalbanin** [comment]
Hi @tonyuride, how often does this happen? Do you create an issue here or reach out to our support team every time it does? If not, how does it get resolved?
