### ISSUE TITLE
Apple Push Notification Key Identification

### ISSUE THREAD

**Issue by sagas29** [Autofleet/locomotion#853]
Hi team,

I am Jesus Sagastume from Uride, we are trying to clean our Apple Store Connect console, and we want to know which key you use to send iOS push notifications.

Keys list
![image](https://github.com/user-attachments/assets/d48dece5-6bf3-4dd6-8e03-b6e273652217)

Thanks!

**Comment by Porat34** [comment]
Hi Jesus,
We use OneSignal and a P12 certification. 
Regarding the keys you sent:
The first key was created by QUP
And the second key we are not sure, but it doesn't seem to be related to us
In any case, we don't recommend to delete keys because we are not sure what the access for those keys are

**Comment by sagas29** [comment]
Thanks for the clarification @Porat34
