### ISSUE TITLE
AutoFleet API: Error fetching active ride data

### ISSUE THREAD

**Issue by joseuride** [Autofleet/locomotion#856]
I am experiencing a timeout error when fetching data from this API: https://client.staging.eu.autofleet.io/api/v1/rides/active. Sometimes it works, and other times it doesn’t. Could you take a look into this?

```
curl --location 'https://client.staging.eu.autofleet.io/api/v1/rides/active' \
--header 'Authorization: Bearer {{accessToken}}' \
--header 'x-loco-ds-id: demandSourceId' \
--header 'x-loco-op-id: demandSourceId'
```

**Comment by OmerGery** [comment]
Hey @joseuride , Please share the trace ids so we can look into it 
Thanks

**Comment by joseuride** [comment]
Hi @OmerGery , I lost the trace ids. If I encounter this issue again, I will send them to you.

**Comment by OmerGery** [comment]
okay, please re open with traces when there is anything specific. Thanks
